export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GENERATE_AND_SEND_OTP = "GENERATE_AND_SEND_OTP";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const CHECK_EMAIL = "CHECK_EMAIL";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const ADD_USER = "ADD_USER";
export const LOAD_LOGIN = "LOAD_LOGIN";

export const GET_ALL_STANDARDS = "GET_ALL_STANDARDS";
export const GET_CURRENT_STANDARD = "GET_CURRENT_STANDARD";
export const GET_TOTAL_STANDARD = "GET_TOTAL_STANDARD";
export const CHECK_DUPLICATE_STANDARD = "CHECK_DUPLICATE_STANDARD";
export const ADD_STANDARD = "ADD_STANDARD";
export const UPDATE_STANDARD = "UPDATE_STANDARD";
export const DELETE_STANDARD = "DELETE_STANDARD";

export const GET_ALL_DIVISIONS = "GET_ALL_DIVISIONS";
export const GET_CURRENT_DIVISION = "GET_CURRENT_DIVISION";
export const GET_TOTAL_DIVISION = "GET_TOTAL_DIVISION";
export const DELETE_DIVISION = "DELETE_DIVISION";
export const ADD_DIVISION = "ADD_DIVISION";
export const UPDATE_DIVISION = "UPDATE_DIVISION";

export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const GET_CURRENT_ROLE = "GET_CURRENT_ROLE";
export const ADD_ROLE = "ADD_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";

export const GET_ALL_USERROLES = "GET_ALL_USERROLES";
export const GET_CURRENT_USERROLE = "GET_CURRENT_USERROLE";
export const GET_TOTAL_USERROLES = "GET_TOTAL_USERROLES";
export const ADD_USERROLE = "ADD_USERROLE";
export const UPDATE_USERROLE = "UPDATE_USERROLE";
export const DELETE_USERROLE = "DELETE_USERROLE";

export const GET_ALL_GRADES = "GET_ALL_GRADES";
export const GET_CURRENT_GRADE = "GET_CURRENT_GRADE";
export const GET_TOTAL_GRADES = "GET_TOTAL_GRADES";
export const ADD_GRADE = "ADD_GRADE";
export const UPDATE_GRADE = "UPDATE_GRADE";
export const DELETE_GRADE = "DELETE_GRADE";

export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS";

export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_CURRENT_STUDENT = "GET_CURRENT_STUDENT";
export const ADD_STUDENT = "ADD_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";

export const GET_ALL_TESTS = "GET_ALL_TESTS";
export const GET_CURRENT_TEST = "GET_CURRENT_TEST";
export const ADD_TEST = "ADD_TEST";
export const UPDATE_TEST = "UPDATE_TEST";
export const DELETE_TEST = "DELETE_TEST";

export const GET_ALL_TEST_RESULTS = "GET_ALL_TEST_RESULTS";
export const ADD_RESULT = "ADD_RESULT";
export const DELETE_RESULT = "DELETE_RESULT";

export const GET_ALL_REPORTS = "GET_ALL_REPORTS";
export const ADD_REPORT = "ADD_REPORT";
export const GET_TOTAL_REPORTS = "GET_TOTAL_REPORTS";
export const ADD_REMARK = "ADD_REMARK";
export const SEND_REPORT = "SEND_REPORT";
export const DELETE_REPORT = "DELETE_REPORT";
